// import ArticleList from '@/components/ArticlesList'
import React, { useEffect } from "react";
import { Col, Row } from "antd";
import NavHome from '../components/NavHome'
import Head from 'next/head'
import TabelaConsultaPlano from "./admin/principal/TabelaConsultaPlano";
import TabelaConsultaSUS from "./admin/principal/TabelaConsultaSUS";

export default function Home() {

  return (
    <>
      <Head>
        <title>Clínica Popular</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavHome />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <Row gutter={[10,10]}>
            <Col span={24}>
              <div className="row border-bottom">
                <h3> Lista de Consultas com Plano</h3>
                <TabelaConsultaPlano />
              </div>
            </Col>
            <Col span={24}>
              <div className="row border-bottom">
                <h3> Lista de Consultas pelo SUS</h3>
                <TabelaConsultaSUS />
              </div>
            </Col>
          </Row>
        </div>
      </div>
    </>
  )
}


